"""
Django settings for tracer project.

Generated by 'django-admin startproject' using Django 1.11.28.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u&l9*asorh8y@8x5h$lu$7rh*tnbp^-p0_sw)95gn@f_k*1#n7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #自定义的中间件
    'web.middleware.auth.AuthMiddleWare',
]

ROOT_URLCONF = 'tracer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tracer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

#Form自验证的字段出错时，显示的错误信息会变成中文
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

#影响数据库自动生成时间的字段若为True则数据库中自动生成的时间应用的是UTC时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# 腾讯云短信应用的 app_id
TENCENT_SMS_APP_ID =0

# 腾讯云短信应用的 app_key
TENCENT_SMS_APP_KEY = ""

# 腾讯云短信签名内容
TENCENT_SMS_SIGN = "我帮你你帮我"

#云短信的正文模板管理的模板ID
TENCENT_SMS_TEMPLATE = {
    'register': 0,
    'login':0
}

#url白名单，不需要登录也能访问的页面 每个路径前面有个斜杠表示根目录，不像urls.py文件中前面没有斜杠  列表里面的url一定要和urls.py文件中定义的一样，元素之间逗号别忘了
WHITE_REGEX_URL_LIST=[
    "/register/",
    "/send/sms/",
    "/login/sms/", #这里的路径少加了最后的一个斜杠，导致了一个BUG，短信验证码登录按钮没效果，被一直重定向
    "/login/",
    "/image_code/",
    "/idnex/",
    "/price/",
]

TENCENT_COS_ID = 'COS的secret_id'
TENCENT_COS_KEY = 'COS的secret_key'


try:
    from .local_settings import *
except ImportError:
    pass