# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-24 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目'),
        ),
    ]
